// Step1: 環境設定 //

-- ロールの指定
USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;

-- クロスリージョン推論の有効化
ALTER ACCOUNT SET CORTEX_ENABLED_CROSS_REGION = 'ANY_REGION';



// Step2: 各種オブジェクトの作成 //

-- データベースの作成
CREATE OR REPLACE DATABASE SNOWRETAIL_DB;
-- スキーマの作成
CREATE OR REPLACE SCHEMA SNOWRETAIL_DB.SNOWRETAIL_SCHEMA;
-- スキーマの指定
USE SCHEMA SNOWRETAIL_DB.SNOWRETAIL_SCHEMA;

-- ステージの作成
CREATE OR REPLACE STAGE SNOWRETAIL_DB.SNOWRETAIL_SCHEMA.FILE DIRECTORY = (ENABLE = TRUE);
CREATE OR REPLACE STAGE SNOWRETAIL_DB.SNOWRETAIL_SCHEMA.SEMANTIC_MODEL_STAGE DIRECTORY = (ENABLE = TRUE);



// Step3: 公開されているGitからデータとスクリプトを取得 //

-- Git連携のため、API統合を作成する
CREATE OR REPLACE API INTEGRATION git_api_integration
  API_PROVIDER = git_https_api
  API_ALLOWED_PREFIXES = ('https://github.com/snow-jp-handson-org/')
  ENABLED = TRUE;

-- GIT統合の作成
CREATE OR REPLACE GIT REPOSITORY GIT_INTEGRATION_FOR_HANDSON
  API_INTEGRATION = git_api_integration
  ORIGIN = 'https://github.com/snow-jp-handson-org/cortex-handson-jp.git';

-- チェックする
ls @GIT_INTEGRATION_FOR_HANDSON/branches/pub_20250709;

-- Githubからファイルを持ってくる
COPY FILES INTO @SNOWRETAIL_DB.SNOWRETAIL_SCHEMA.FILE FROM @GIT_INTEGRATION_FOR_HANDSON/branches/pri_20250901/data/;
COPY FILES INTO @SNOWRETAIL_DB.SNOWRETAIL_SCHEMA.SEMANTIC_MODEL_STAGE FROM @GIT_INTEGRATION_FOR_HANDSON/branches/pri_20250901/handson/sales_analysis_model.yaml;



// Step4: テーブルの作成とデータロード //

-- 店舗データwith商品マスタテーブルの作成
CREATE OR REPLACE TABLE RETAIL_DATA_WITH_PRODUCT_MASTER (
	PRODUCT_ID_MASTER VARCHAR,
	PRODUCT_NAME_MASTER VARCHAR,
	UNIT_PRICE_MASTER NUMBER,
	TRANSACTION_ID VARCHAR,
	TRANSACTION_DATE DATE,
	PRODUCT_NAME VARCHAR,
	QUANTITY NUMBER,
	UNIT_PRICE NUMBER,
	TOTAL_PRICE NUMBER,
	SIMILARITY FLOAT
);

-- ECデータwith商品マスタテーブルの作成
CREATE OR REPLACE TABLE EC_DATA_WITH_PRODUCT_MASTER (
	PRODUCT_ID_MASTER VARCHAR,
	PRODUCT_NAME_MASTER VARCHAR,
	UNIT_PRICE_MASTER NUMBER,
	TRANSACTION_ID VARCHAR,
	TRANSACTION_DATE DATE,
	PRODUCT_NAME VARCHAR,
	QUANTITY NUMBER,
	UNIT_PRICE NUMBER,
	TOTAL_PRICE NUMBER,
	SIMILARITY FLOAT
);

-- ファイルフォーマットの作成
CREATE OR REPLACE TEMP FILE FORMAT temp_ff
    TYPE = csv
    SKIP_HEADER = 1
;

-- データロード
COPY INTO RETAIL_DATA_WITH_PRODUCT_MASTER
FROM @FILE
FILE_FORMAT = (FORMAT_NAME = temp_ff)
FILES = ('retail_data_with_product_master.csv');

COPY INTO EC_DATA_WITH_PRODUCT_MASTER
FROM @FILE
FILE_FORMAT = (FORMAT_NAME = temp_ff)
FILES = ('ec_data_with_product_master.csv');



// Step5: Snowflake Intelligenceの環境準備 //

-- Intelligence用のデータベース作成と権限付与
CREATE DATABASE IF NOT EXISTS snowflake_intelligence;
GRANT USAGE ON DATABASE snowflake_intelligence TO ROLE PUBLIC;

-- Intelligence用のスキーマ作成と権限付与
CREATE SCHEMA IF NOT EXISTS snowflake_intelligence.agents;
GRANT USAGE ON SCHEMA snowflake_intelligence.agents TO ROLE PUBLIC;

-- エージェントを作成する権限をPUBLICロールに付与
GRANT CREATE AGENT ON SCHEMA snowflake_intelligence.agents TO ROLE PUBLIC;



// (Option) 後片付け

-- データベースと関連オブジェクトの削除
-- Streamlit、Git統合、各種テーブルなどが全て削除されます
-- DROP DATABASE SNOWRETAIL_DB;
-- DROP DATABASE SNOWFLAKE_INTELLIGENCE;

-- API統合の削除
-- DROP API INTEGRATION git_api_integration;

-- クロスリージョン推論の無効化
-- (有効のままで問題無ければ実行しなくても構いません)
-- ALTER ACCOUNT UNSET CORTEX_ENABLED_CROSS_REGION;
